### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chch1019** [aaronboda24/Loose-GNSS-IMU#10]
Hi,
I am getting a "Segmentation fault (core dumped)" error when I try to run for my data (it is working fine with the example data you have provided). I have printed out the values, my data was read by the reader provided in this package. I don't know much C++, Could you help me get through this?.

Thanks,
cck

**Comment by aaronboda24** [comment]
Sorry I cannot help with that, you'll need to troubleshoot it.
