### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by haibo9916** [aaronboda24/Loose-GNSS-IMU#12]
Dear author, I don't understand why you don't apply GNSS data calculation in standard RINEX format. I don't know how to generate your data format?

**Comment by aaronboda24** [comment]
Intention of this software is not processing of RINEX data. 

You can use RTKLib to process your RINEX data. Then you will need to create a script to prepare that output in the format seen in the sample file. 

Sample GNSS input file is located here: Loose-GNSS-IMU/Loose-GNSS-IMU/Input/GNSS.txt
