### ISSUE TITLE
papers

### ISSUE THREAD

**Issue by liyuebit** [aaronboda24/Loose-GNSS-IMU#2]
Hello，
Is there any paper about your work？ If yes, can you give me a URL or paper name?
Thkan you.

**Comment by aaronboda24** [comment]
I don't have any papers for this work, but I am working on a tightly coupled fusion method. If you are interested, I found useful information from Paul Groves' textbook : Principles of GNSS, Inertial, and Multisensor Integrated Navigation Systems, 2nd Edition.
