### ISSUE TITLE
What is COV PVxyz？

### ISSUE THREAD

**Issue by zhangshengkai520** [aaronboda24/Loose-GNSS-IMU#5]
Hi， I am shengkai, i am very interested on your fusion code. But there has little part made  me confuse. In the GPS input file, what is the COV PV xyz? how to get it ?

**Comment by aaronboda24** [comment]
It refers to covariance between position and velocity states. You can set them as 0. 

I computed the GNSS states using a position-velocity kalman filter. Based on the system model I used, the position and velocity states have some correlation.

See more clarification here: [GNSS Input Parameters ](https://github.com/aaronboda24/Loose-GNSS-IMU/issues/1)
