### ISSUE TITLE
there is a problem about running your code

### ISSUE THREAD

**Issue by zhangshengkai520** [aaronboda24/Loose-GNSS-IMU#6]
![image](https://user-images.githubusercontent.com/33276990/68738562-9c0ce680-0621-11ea-8125-767713d14fac.png)

When I running your code there always report this error(in the IMUmechECEF file）, Do you know how to solve it? 
Or some new update code?  

Thanks for your sharing.  
Have a nice day.

**Comment by zhangshengkai520** [comment]
I try to running this code on QTcreator, but nothing happened.  Later I will try to run it on VS2017, Sorry to open this issues. I will update new information later.

**Comment by zhangshengkai520** [comment]
VS2017 there also has some errors, could you update your code ? Thanks. have a nice day.

**Comment by aaronboda24** [comment]
I don't see any issues in IMUmechECEF file. Please provide more details.
