### ISSUE TITLE
About the result pictures

### ISSUE THREAD

**Issue by SUQIGUANG** [aaronboda24/Loose-GNSS-IMU#7]
Good job,man! I appreciate your work, you give a whole process about loose coupled data fusion. Can you tell me how do you draw the result picture? Is there any script that can draw the pics? Waiting for your apply : )

**Comment by aaronboda24** [comment]
Thanks for your comment. 
I used Matlab for the plots. Please refer to https://www.mathworks.com/help/matlab/ref/plot.html
