### ISSUE TITLE
Lack of explanation on GNSS inputs.

### ISSUE THREAD

**Issue by tomtom13** [aaronboda24/Loose-GNSS-IMU#8]
Hi, this is not much of an use, because there is no documentation / code on GNS input. Usually GNSS comes in in NMEA2000, this code however takes it in XYZ (fair enough it's ECEF), but further data x xy xz y yz z is not explained / has any code how to process this data.

**Comment by aaronboda24** [comment]
GNSS input parameters explained here: https://github.com/aaronboda24/Loose-GNSS-IMU/issues/1
This was a side project for exploration and learning.

**Comment by tomtom13** [comment]
Ok, I got carried away with last comment, however when you close issues, nobody digs through issues to find information. Fact that you can set variance and covariance to 0 IS important, and should be part of at least readme. Additionally, info on how to generate variance and covariance would help people a lot on trying to reproduce best results. I was half way through reading through the code and found this bit and I was fuming that I might just wasted my time. Anyway, sorry for last comment - still please provide better documentation around this fact. 

Also I see that there are mentions of inertia frame - ECI ? if so, which one ? J2000 ? is this model is going to rotate with earth and consider centrifugal forces acting on the object due to following earth rotation etc.
